<?php
# This file was automatically generated by the MediaWiki 1.29.0-wmf.18
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}

## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Βικιταξίδια";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "/elwv";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "http://localhost";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/Wikivoyage-el.png";

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@localhost";
$wgPasswordSender = "apache@localhost";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "elwikivoyage";
$wgDBuser = "root";
$wgDBpassword = "fakepassword";

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 5.0.
$wgDBmysql5 = false;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = true;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = false;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "en_US.utf8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publically accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "el";

$wgSecretKey = "stuffwhichhasbeenremoved";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "morestuffwhichhasbeenremoved";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-sa/4.0/";
$wgRightsText = "Creative Commons Αναφορά Δημιουργού-Παρόμοια Διανομή";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "vector";

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Vector' );

$wgOverrideHostname = "trouble";

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtensions('ExtensionName');
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'Babel' );
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'Kartographer' );
wfLoadExtension( 'LabeledSectionTransclusion' );
wfLoadExtension( 'PagedTiffHandler' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SiteMatrix' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TimedMediaHandler' );
# wfLoadExtension( 'VisualEditor' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'WikimediaMaintenance' );

# End of automatically generated settings.
# Add more configuration options below.

$wgShowExceptionDetails = true;
$wgContentHandlerUseDB = true;
$wgUseTidy = true;
$wgTidyBin = '/usr/bin/tidy';   
#$wgTidyConf = $IP.'/extensions/tidy/tidy.conf';
$wgShowDebug = true;
$wgDebugLogFile = '/var/www/html/elwv/logs/debuglog.txt';
$wgIncludeLegacyJavaScript = true;

wfLoadExtension( 'ActiveAbstract' );
wfLoadExtension( 'TocTree' );
$wgDefaultUserOptions['toc-floated'] = true;
wfLoadExtension( 'Disambiguator' );
#wfLoadExtension( 'WikibaseClient' );
##$wgEnableWikibaseRepo = false;
#$wmgUseWikibaseRepo = false;
#$wgEnableWikibaseClient = true;
#$wmgUseWikibaseClient = true;

#require_once( "$IP/extensions/Wikidata/Wikidata.php" );

$wgWBClientSettings['repoSiteName'] = 'wikibase-repo-name';
$baseNs = 120;
// Define the namespace indexes for repo (and client wikis also need to be aware of these,
// thus entityNamespaces need to be a shared setting).
//
// NOTE: do *not* define WB_NS_ITEM and WB_NS_ITEM_TALK when using a core namespace for items!
define( 'WB_NS_PROPERTY', $baseNs );
define( 'WB_NS_PROPERTY_TALK', $baseNs + 1 );
define( 'WB_NS_QUERY', $baseNs + 2 );
define( 'WB_NS_QUERY_TALK', $baseNs + 3 );


$wgWBSharedSettings['entityNamespaces'] = [
	'item' => NS_MAIN,
	'property' => WB_NS_PROPERTY
];

$wgWBSharedSettings['specialSiteLinkGroups'][] = 'wikidata';

$wgWBClientSettings = $wgWBSharedSettings + $wgWBClientSettings;

// to be safe, keeping this here although $wgDBname is default setting
$wgWBClientSettings['siteGlobalID'] = $wgDBname;

$wgWBClientSettings['changesDatabase'] = 'wikidatawiki';
$wgWBClientSettings['repoDatabase'] = 'wikidatawiki';

$wgWBClientSettings['repoNamespaces'] = [
	'item' => '',
	'property' => 'Property'
];

$wgWBClientSettings['languageLinkSiteGroup'] = 'wikivoyage';

$wgWBClientSettings['siteGroup'] = 'wikivoyage';
$wgWBClientSettings['otherProjectsLinksByDefault'] = true;

$wgWBClientSettings['excludeNamespaces'] = function() {
	// @fixme 102 is LiquidThread comments on wikinews and elsewhere?
	// but is the Extension: namespace on mediawiki.org, so we need
	// to allow wiki-specific settings here.
	return array_merge(
		MWNamespace::getTalkNamespaces(),
		// 90 => LiquidThread threads
		// 92 => LiquidThread summary
		// 118 => Draft
		// 1198 => NS_TRANSLATE
		// 2600 => Flow topic
		[ NS_USER, NS_FILE, NS_MEDIAWIKI, 90, 92, 118, 1198, 2600 ]
	);
};

$wmgWikibaseClientSettings = [];

foreach( $wmgWikibaseClientSettings as $setting => $value ) {
	$wgWBClientSettings[$setting] = $value;
}

$wgWBClientSettings['allowDataTransclusion'] = true;
$wgWBClientSettings['allowDataAccessInUserLanguage'] = false;
$wgWBClientSettings['entityAccessLimit'] = 400;

// fixme find out what the hell this is
$wgWBClientSettings['sharedCacheKeyPrefix'] = 'removed';
$wgWBClientSettings['sharedCacheDuration'] = 60 * 60 * 24;

$wgWBClientSettings['repoUrl'] = 'https://www.wikidata.org';
$wgWBClientSettings['repoConceptBaseUri'] = 'http://www.wikidata.org/entity/';
$wgArticlePlaceholderImageProperty = 'P18';

$wgWBClientSettings['badgeClassNames'] = [
	'Q17437796' => 'badge-featuredarticle',
	'Q17437798' => 'badge-goodarticle',
	'Q17559452' => 'badge-recommendedarticle', // T72268
	'Q17506997' => 'badge-featuredlist', // T72332
	'Q17580674' => 'badge-featuredportal', // T75193
	'Q20748091' => 'badge-notproofread', // T97014 - Wikisource badges
	'Q20748094' => 'badge-problematic',
	'Q20748092' => 'badge-proofread',
	'Q20748093' => 'badge-validated',
	'Q28064618' => 'badge-digitaldocument', // T153186
];

// Overwrite or add commons links in the "other projects sidebar" with the "commons category" (P373), per T126960
$wgWikimediaBadgesCommonsCategoryProperty = $wgDBname === 'commonswiki' ? null : 'P373';

$wgArticlePlaceholderSearchEngineIndexed = false;
$wgWBClientSettings['propertyOrderUrl'] = 'https://www.wikidata.org/w/index.php?title=MediaWiki:Wikibase-SortedProperties&action=raw&sp_ver=1';

#$wgReadOnly = "this is a test. [https://meta.wikimedia.org/wiki/Special:MyLanguage/Tech/Server_switch_2017]";
$wgLBFactoryConf = [
'class' => 'LBFactoryMulti',
'sectionsByDB' => [
],
# Load lists
#
# Masters should be in slot [0].
#
# All servers for which replication lag matters should be in the load
# list, not commented out, because otherwise maintenance scripts such
# as compressOld.php won't wait for those servers when they lag.
#
# Conversely, all servers which are down or do not replicate should be
# removed, not set to load zero, because there are certain situations
# when load zero servers will be used, such as if the others are lagged.
# Servers which are down should be removed to avoid a timeout overhead
# per invocation.
#
# Additionally, if a server should not to be lagged (for example,
# an api node, or a recentchanges node, set the load to at least 1.
# This will make the node be taken into account on the wait for lag
# function (the master is not included, as by definition has lag 0).
'sectionLoads' => [
	'DEFAULT' => [
		'localhost' => 0,
	],
],
'serverTemplate' => [
	'dbname'	  => $wgDBname,
	'user'		  => $wgDBuser,
	'password'	  => $wgDBpassword,
	'type'		  => 'mysql',
	'flags'		  => DBO_DEFAULT,
	'max lag'	  => 6, // should be safely less than $wgCdnReboundPurgeDelay
	'variables'   => [
		'innodb_lock_wait_timeout' => 15
	]
],
'templateOverridesByCluster' => [
],
'masterTemplateOverrides' => [
],
'externalTemplateOverrides' => [
],
'externalLoads' => [
	'extension1' => [
		'localhost' => 0,
	],
],
'groupLoadsByDB' => [],
'hostsByName' => [
    'localhost'  => '127.0.0.1',
],
'templateOverridesBySection' => [
],
'readOnlyBySection' => [
#    'DEFAULT' => 'MediaWiki is in read-only mode for a datacenter switchover test. https://meta.wikimedia.org/wiki/codfw Please try again in a few minutes.',
#    'DEFAULT' => "this is a test. [https://meta.wikimedia.org/wiki/Special:MyLanguage/Tech/Server_switch_2017]",
],
];


wfLoadExtension( 'Flow' );
$wgShowDBErrorBacktrace = true;

//$wgContentHandlerUseDB = false;
$wgNamespaceContentModels[NS_TALK] = 'flow-board';
$wgFlowSearchEnabled = false;
$wgFlowContentFormat = 'wikitext';
$wgFlowCluster = 'extension1';
